spring:

  application:
    name: authSys

  config:
    import: classpath:permissions.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: postgres

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  webflux:
    problemdetails:
      enabled: true

logging:
  level:
    org.springframework.security: INFO
    com.techStack.authSys.authorization: DEBUG