// separate file
package com.techStack.authSys.tour.models;

public enum ActivityAction {
    STATUS_CHANGED, ASSIGNED, QUOTE_CREATED, QUOTE_SENT,
    QUOTE_ACCEPTED, QUOTE_DECLINED, NOTE_ADDED, APPRECIATION_SENT,
    PAYMENT_REJECTED,PAYMENT_VERIFIED, PAYMENT_SUBMITTED,
    BOOKING_CREATED,
}
