package com.techStack.authSys.models.audit;

public enum ActionType {
    LOGIN_SUCCESS,
    PASSWORD_CHANGE,
    ROLE_MODIFICATION,
    TOKEN_REVOCATION,
    REGISTRATION,
    PRIVILEGE_ESCALATION,
    EMAIL_VERIFICATION,
    ACCOUNT_DISABLED,
    PASSWORD_REUSE_ENFORCEMENT_FAILURE,
    SUPER_ADMIN_CREATED,
    ADMIN_CREATED,
    LOGIN,
    FIRST_LOGIN,
    BLOCKED,
    LOGIN_FAILED,
    LOGOUT,
    USER_APPROVAL_FAILED,
    EMAIL_FAILURE,
    EMAIL_SENT,
    USER_APPROVED,
    PASSWORD_CHANGED
}
