package com.techStack.authSys.booking.models;

import com.techStack.authSys.availability.models.TourAvailability;
import com.techStack.authSys.common.models.BaseEntity;
import com.techStack.authSys.tour.models.Tour;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(
        name = "bookings",
        indexes = {
                @Index(name = "idx_bookings_customer_id",      columnList = "customer_id"),
                @Index(name = "idx_bookings_tour_id",          columnList = "tour_id"),
                @Index(name = "idx_bookings_availability_id",  columnList = "availability_id"),
                @Index(name = "idx_bookings_status",           columnList = "status"),
                @Index(name = "idx_bookings_tour_date",        columnList = "tour_date")
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Booking extends BaseEntity {

    // ── Reference ────────────────────────────────────────────────────────────

    /**
     * Human-readable reference shown to customers and staff (e.g. support
     * calls, vouchers) — the UUID id is still the real primary key.
     * Generated by BookingService.generateBookingReference() at creation.
     */
    @NotBlank
    @Column(name = "booking_reference", nullable = false, unique = true, length = 20)
    private String bookingReference;

    // ── Customer ─────────────────────────────────────────────────────────────

    /**
     * Firebase UID — ties this booking to a User in authSys.
     * Stored as plain string (not a FK) because User lives in Firestore,
     * not in the same PostgreSQL database as bookings.
     */
    @NotBlank
    @Column(name = "customer_id", nullable = false, length = 128)
    private String customerId;

    @NotBlank
    @Email
    @Column(name = "customer_email", nullable = false, length = 255)
    private String customerEmail;

    @NotBlank
    @Column(name = "customer_name", nullable = false, length = 255)
    private String customerName;

    // ── Tour reference ────────────────────────────────────────────────────────

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(
            name = "tour_id",
            nullable = false,
            foreignKey = @ForeignKey(name = "fk_booking_tour")
    )
    private Tour tour;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(
            name = "availability_id",
            nullable = false,
            foreignKey = @ForeignKey(name = "fk_booking_availability")
    )
    private TourAvailability availability;

    /**
     * Denormalized from availability.date — allows date-range queries
     * and reporting without joining tour_availability every time.
     */
    @NotNull
    @Column(name = "tour_date", nullable = false)
    private LocalDate tourDate;

    /**
     * Denormalized from enquire-button.tsx.name — preserves the display name even if
     * the enquire-button.tsx is later renamed, soft-deleted, or archived.
     */
    @NotBlank
    @Column(name = "tour_name", nullable = false, length = 150)
    private String tourName;

    // ── Party ──────────────────────────────────────────────────────────────────

    /**
     * numberOfAdults + numberOfChildren, denormalized here (same pattern as
     * tourName/tourDate below) because it's checked constantly — capacity
     * guards, duplicate-booking checks, traveler-list validation — without
     * summing two fields every time. BookingService keeps it in sync at
     * creation; it is not independently settable after that.
     */
    @NotNull
    @Min(1)
    @Column(name = "traveler_count", nullable = false)
    private Integer travelerCount;

    @NotNull
    @Min(0)
    @Column(name = "number_of_adults", nullable = false)
    @Builder.Default
    private Integer numberOfAdults = 0;

    @NotNull
    @Min(0)
    @Column(name = "number_of_children", nullable = false)
    @Builder.Default
    private Integer numberOfChildren = 0;

    /** Alias for travelerCount, matching the "totalGuests" language customers see. */
    public int getTotalGuests() {
        return travelerCount;
    }

    @OneToMany(
            mappedBy = "booking",
            cascade = CascadeType.ALL,
            orphanRemoval = true,
            fetch = FetchType.LAZY
    )
    @Builder.Default
    private List<BookingTraveler> travelers = new ArrayList<>();

    // ── Pricing snapshot ───────────────────────────────────────────────────────

    @NotNull
    @DecimalMin("0.00")
    @Column(name = "price_per_traveler", nullable = false, precision = 10, scale = 2)
    private BigDecimal pricePerTraveler;

    /** pricePerTraveler * travelerCount, before discount. */
    @NotNull
    @DecimalMin("0.00")
    @Column(name = "subtotal", nullable = false, precision = 10, scale = 2)
    private BigDecimal subtotal;

    @NotNull
    @DecimalMin("0.00")
    @Column(name = "discount", nullable = false, precision = 10, scale = 2)
    @Builder.Default
    private BigDecimal discount = BigDecimal.ZERO;

    /** Net payable = subtotal - discount. This is what deposit/balance/payments are measured against. */
    @NotNull
    @DecimalMin("0.00")
    @Column(name = "total_price", nullable = false, precision = 10, scale = 2)
    private BigDecimal totalPrice;

    @NotBlank
    @Column(name = "currency", nullable = false, length = 3)
    @Builder.Default
    private String currency = "KES";

    // ── Payment tracking ─────────────────────────────────────────────────────

    /**
     * Required deposit to move a PENDING booking toward CONFIRMED.
     * Typically enquire-button.tsx.depositPercentage * totalPrice, set by BookingService
     * at creation. 0 means full payment is required upfront.
     */
    @NotNull
    @DecimalMin("0.00")
    @Column(name = "deposit_amount", nullable = false, precision = 10, scale = 2)
    private BigDecimal depositAmount;

    /** Running total of payments received. Updated only via recordPayment(). */
    @NotNull
    @DecimalMin("0.00")
    @Column(name = "amount_paid", nullable = false, precision = 10, scale = 2)
    @Builder.Default
    private BigDecimal amountPaid = BigDecimal.ZERO;

    /** totalPrice - amountPaid, floored at zero. Kept in sync by recordPayment(). */
    @NotNull
    @DecimalMin("0.00")
    @Column(name = "balance_amount", nullable = false, precision = 10, scale = 2)
    private BigDecimal balanceAmount;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "payment_status", nullable = false, length = 20)
    @Builder.Default
    private PaymentStatus paymentStatus = PaymentStatus.UNPAID;

    // ── Lifecycle ──────────────────────────────────────────────────────────────

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 30)
    @Builder.Default
    private BookingStatus status = BookingStatus.PENDING_PAYMENT;

    // ── Payment ────────────────────────────────────────────────────────────────

    @Column(name = "payment_reference", length = 255)
    private String paymentReference;

    @Column(name = "paid_at")
    private Instant paidAt;

    // ── Cancellation / refund ──────────────────────────────────────────────────

    @Column(name = "cancelled_at")
    private Instant cancelledAt;

    @Size(max = 500)
    @Column(name = "cancellation_reason", length = 500)
    private String cancellationReason;

    @Column(name = "refund_reference", length = 255)
    private String refundReference;

    @Column(name = "refunded_at")
    private Instant refundedAt;

    // ── Customer notes ─────────────────────────────────────────────────────────

    @Size(max = 1000)
    @Column(name = "special_requests", length = 1000)
    private String specialRequests;

    // ── Convenience methods ────────────────────────────────────────────────────

    /**
     * Adds a traveler and sets the back-reference.
     * Always use this instead of getTravelers().add() directly.
     */
    public void addTraveler(BookingTraveler traveler) {
        travelers.add(traveler);
        traveler.setBooking(this);
    }

    /**
     * Removes a traveler and clears the back-reference.
     */
    public void removeTraveler(BookingTraveler traveler) {
        travelers.remove(traveler);
        traveler.setBooking(null);
    }

    /**
     * Manually confirms a PENDING booking without recording a payment —
     * for staff overrides or pay-on-arrival arrangements. For the normal
     * flow (deposit or full payment received), use recordPayment() instead,
     * which auto-confirms.
     */
    public void confirm() {
        if (this.status != BookingStatus.PENDING_PAYMENT) {
            throw new IllegalStateException(
                    "Only PENDING bookings can be confirmed. Current: "
                            + this.status.name());
        }
        this.status = BookingStatus.CONFIRMED;
    }

    /**
     * Records a payment (deposit or balance) against this booking.
     * Updates amountPaid, recomputes balanceAmount, and moves paymentStatus
     * to PARTIALLY_PAID or PAID. A PENDING booking is auto-confirmed the
     * moment any payment is received — this is the normal path to CONFIRMED.
     */
    public void recordPayment(BigDecimal amount, String paymentReference) {
        if (amount == null || amount.signum() <= 0) {
            throw new IllegalArgumentException("Payment amount must be positive");
        }
        if (this.status == BookingStatus.CANCELLED || this.status == BookingStatus.NO_SHOW) {
            throw new IllegalStateException(
                    "Cannot record payment on a " + this.status.name() + " booking");
        }
        this.amountPaid = this.amountPaid.add(amount);
        this.balanceAmount = this.totalPrice.subtract(this.amountPaid).max(BigDecimal.ZERO);
        this.paymentStatus = this.amountPaid.compareTo(this.totalPrice) >= 0
                ? PaymentStatus.PAID
                : PaymentStatus.PARTIALLY_PAID;
        this.paymentReference = paymentReference;
        this.paidAt = Instant.now();
        if (this.status == BookingStatus.PENDING_PAYMENT) {
            this.status = BookingStatus.CONFIRMED;
        }
    }

    /**
     * Cancels this booking.
     * Sets status → CANCELLED, records reason and timestamp, soft-deletes.
     * Slot release is handled by BookingService before calling this method.
     * Does NOT touch paymentStatus — issuing a refund is a separate,
     * explicit action via refundPayment().
     */
    public void cancel(String reason) {
        if (!status.isCancellable()) {
            throw new IllegalStateException(
                    "Cannot cancel a booking in status: " + status.name());
        }
        this.status = BookingStatus.CANCELLED;
        this.cancelledAt = Instant.now();
        this.cancellationReason = reason;
        this.setDeleted(true);
    }

    /**
     * Marks payment as refunded after money is returned to the customer.
     * Booking must already be CANCELLED, and must have received some
     * payment (PARTIALLY_PAID or PAID) to refund.
     */
    public void refundPayment(String refundReference) {
        if (this.status != BookingStatus.CANCELLED) {
            throw new IllegalStateException(
                    "Only CANCELLED bookings can be refunded. Current: "
                            + this.status.name());
        }
        if (this.paymentStatus != PaymentStatus.PAID
                && this.paymentStatus != PaymentStatus.PARTIALLY_PAID) {
            throw new IllegalStateException(
                    "No payment to refund — current payment status: "
                            + this.paymentStatus.name());
        }
        this.paymentStatus = PaymentStatus.REFUNDED;
        this.refundReference = refundReference;
        this.refundedAt = Instant.now();
    }

    /**
     * Marks this booking as COMPLETED after the enquire-button.tsx has run.
     * Must be CONFIRMED first.
     */
    public void complete() {
        if (this.status != BookingStatus.CONFIRMED) {
            throw new IllegalStateException(
                    "Only CONFIRMED bookings can be completed. Current: "
                            + this.status.name());
        }
        this.status = BookingStatus.COMPLETED;
    }

    /**
     * Marks a CONFIRMED booking as NO_SHOW — the customer didn't show up.
     * Does not release the slot or touch payment; no-show policy (refund
     * or not) is a separate business decision made via refundPayment() if
     * applicable, since most operators don't refund no-shows.
     */
    public void markNoShow() {
        if (this.status != BookingStatus.CONFIRMED) {
            throw new IllegalStateException(
                    "Only CONFIRMED bookings can be marked NO_SHOW. Current: "
                            + this.status.name());
        }
        this.status = BookingStatus.NO_SHOW;
    }
}